/**
 * Report HTML generation and export
 */

import { formatKg, formatPercent, formatDateTime } from '../utils/format.js';

/**
 * Generate a self-contained HTML report for a scan
 * @param {Object} scan - The scan object
 * @returns {string} Complete HTML document as string
 */
export function generateReportHtml(scan) {
  const totalResidualKg = scan.totalResidualKg || 0;
  const extractedKg = scan.streams.reduce((sum, s) => sum + (s.weightKg || 0), 0);
  const remainingKg = Math.max(0, totalResidualKg - extractedKg);
  const separationPct = totalResidualKg > 0 ? (extractedKg / totalResidualKg * 100) : 0;
  
  const photoHtml = scan.photo 
    ? `<div class="photo-section">
        <img src="${scan.photo.dataUrl}" alt="Waste scan photo" class="scan-photo">
       </div>`
    : '';
  
  const streamsHtml = scan.streams.length > 0
    ? `<table class="streams-table">
        <thead>
          <tr>
            <th>Waste Stream</th>
            <th>Weight</th>
            <th>% of Total</th>
          </tr>
        </thead>
        <tbody>
          ${scan.streams.map(stream => {
            const pct = totalResidualKg > 0 ? (stream.weightKg / totalResidualKg * 100) : 0;
            return `
              <tr>
                <td>${escapeHtml(stream.name)}</td>
                <td>${formatKg(stream.weightKg)}</td>
                <td>${formatPercent(pct)}</td>
              </tr>
            `;
          }).join('')}
        </tbody>
      </table>`
    : '<p class="no-streams">No waste streams recorded</p>';
  
  const notesHtml = scan.notes 
    ? `<div class="notes-section">
        <h3>Notes</h3>
        <p>${escapeHtml(scan.notes)}</p>
       </div>`
    : '';
  
  const warningHtml = extractedKg > totalResidualKg 
    ? `<div class="warning">
        Note: Extracted weight exceeds total residual weight. Values may be estimates.
       </div>`
    : '';
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Waste Scan Report - ${formatDateTime(scan.createdAt)}</title>
  <style>
    ${getReportStyles()}
  </style>
</head>
<body>
  <div class="report-container">
    <header class="report-header">
      <div class="logo">
        <svg width="40" height="40" viewBox="0 0 40 40" fill="none">
          <circle cx="20" cy="20" r="18" stroke="#00A887" stroke-width="3"/>
          <path d="M20 8C20 8 12 14 12 20C12 26 16 32 20 32C24 32 28 26 28 20C28 14 20 8 20 8Z" fill="#00A887"/>
        </svg>
        <span>Seenons</span>
      </div>
      <h1>Waste Scan Report</h1>
    </header>
    
    <section class="meta-section">
      <div class="meta-item">
        <span class="meta-label">Date</span>
        <span class="meta-value">${formatDateTime(scan.createdAt)}</span>
      </div>
      ${scan.location ? `
      <div class="meta-item">
        <span class="meta-label">Location</span>
        <span class="meta-value">${escapeHtml(scan.location)}</span>
      </div>
      ` : ''}
    </section>
    
    ${photoHtml}
    
    <section class="summary-section">
      <h2>Summary</h2>
      <div class="summary-cards">
        <div class="summary-card">
          <span class="card-label">Total Residual</span>
          <span class="card-value">${formatKg(totalResidualKg)}</span>
        </div>
        <div class="summary-card highlight">
          <span class="card-label">Extractable</span>
          <span class="card-value">${formatKg(extractedKg)}</span>
        </div>
        <div class="summary-card highlight-primary">
          <span class="card-label">Separation Potential</span>
          <span class="card-value">${formatPercent(separationPct)}</span>
        </div>
        <div class="summary-card">
          <span class="card-label">Remaining Residual</span>
          <span class="card-value">${formatKg(remainingKg)}</span>
        </div>
      </div>
      ${warningHtml}
    </section>
    
    <section class="streams-section">
      <h2>Waste Streams Breakdown</h2>
      ${streamsHtml}
    </section>
    
    ${notesHtml}
    
    <footer class="report-footer">
      <p>Generated by Seenons Waste Scan</p>
      <p class="footer-date">Report created: ${new Date().toLocaleString()}</p>
    </footer>
  </div>
  
  <div class="print-button no-print">
    <button onclick="window.print()">Print / Save as PDF</button>
  </div>
</body>
</html>`;
}

/**
 * Get CSS styles for the report
 * @returns {string} CSS styles
 */
function getReportStyles() {
  return `
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      color: #1a2b3c;
      background: #f5f7fa;
      padding: 20px;
    }
    
    .report-container {
      max-width: 800px;
      margin: 0 auto;
      background: white;
      border-radius: 16px;
      box-shadow: 0 4px 24px rgba(0,0,0,0.08);
      overflow: hidden;
    }
    
    .report-header {
      background: linear-gradient(135deg, #00A887 0%, #008B6E 100%);
      color: white;
      padding: 32px;
      text-align: center;
    }
    
    .logo {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 12px;
      margin-bottom: 16px;
    }
    
    .logo svg circle {
      stroke: white;
    }
    
    .logo svg path {
      fill: white;
    }
    
    .logo span {
      font-size: 24px;
      font-weight: 600;
      letter-spacing: -0.5px;
    }
    
    .report-header h1 {
      font-size: 28px;
      font-weight: 600;
      letter-spacing: -0.5px;
    }
    
    .meta-section {
      display: flex;
      gap: 32px;
      padding: 24px 32px;
      background: #f8fafb;
      border-bottom: 1px solid #e8ecef;
    }
    
    .meta-item {
      display: flex;
      flex-direction: column;
      gap: 4px;
    }
    
    .meta-label {
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #6b7c8d;
      font-weight: 500;
    }
    
    .meta-value {
      font-size: 16px;
      font-weight: 500;
      color: #1a2b3c;
    }
    
    .photo-section {
      padding: 24px 32px;
      text-align: center;
    }
    
    .scan-photo {
      max-width: 100%;
      max-height: 400px;
      border-radius: 12px;
      box-shadow: 0 2px 12px rgba(0,0,0,0.1);
    }
    
    .summary-section {
      padding: 32px;
    }
    
    .summary-section h2,
    .streams-section h2,
    .notes-section h3 {
      font-size: 18px;
      font-weight: 600;
      color: #1a2b3c;
      margin-bottom: 20px;
      letter-spacing: -0.3px;
    }
    
    .summary-cards {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 16px;
    }
    
    .summary-card {
      background: #f8fafb;
      border-radius: 12px;
      padding: 20px;
      text-align: center;
    }
    
    .summary-card.highlight {
      background: #e8f5f1;
    }
    
    .summary-card.highlight-primary {
      background: linear-gradient(135deg, #00A887 0%, #008B6E 100%);
      color: white;
    }
    
    .summary-card.highlight-primary .card-label {
      color: rgba(255,255,255,0.85);
    }
    
    .card-label {
      display: block;
      font-size: 13px;
      color: #6b7c8d;
      margin-bottom: 8px;
      font-weight: 500;
    }
    
    .card-value {
      display: block;
      font-size: 28px;
      font-weight: 700;
      letter-spacing: -0.5px;
    }
    
    .warning {
      margin-top: 16px;
      padding: 12px 16px;
      background: #fff3e0;
      border-left: 4px solid #ff9800;
      border-radius: 0 8px 8px 0;
      font-size: 14px;
      color: #e65100;
    }
    
    .streams-section {
      padding: 0 32px 32px;
    }
    
    .streams-table {
      width: 100%;
      border-collapse: collapse;
    }
    
    .streams-table th,
    .streams-table td {
      padding: 14px 16px;
      text-align: left;
      border-bottom: 1px solid #e8ecef;
    }
    
    .streams-table th {
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #6b7c8d;
      font-weight: 600;
      background: #f8fafb;
    }
    
    .streams-table td {
      font-size: 15px;
    }
    
    .streams-table td:first-child {
      font-weight: 500;
    }
    
    .streams-table tr:last-child td {
      border-bottom: none;
    }
    
    .no-streams {
      padding: 24px;
      text-align: center;
      color: #6b7c8d;
      background: #f8fafb;
      border-radius: 8px;
    }
    
    .notes-section {
      padding: 0 32px 32px;
    }
    
    .notes-section p {
      background: #f8fafb;
      padding: 16px;
      border-radius: 8px;
      color: #4a5d6e;
      white-space: pre-wrap;
    }
    
    .report-footer {
      padding: 24px 32px;
      background: #f8fafb;
      border-top: 1px solid #e8ecef;
      text-align: center;
    }
    
    .report-footer p {
      color: #6b7c8d;
      font-size: 13px;
    }
    
    .footer-date {
      margin-top: 4px;
      font-size: 12px !important;
    }
    
    .print-button {
      position: fixed;
      bottom: 24px;
      right: 24px;
    }
    
    .print-button button {
      background: #00A887;
      color: white;
      border: none;
      padding: 14px 28px;
      font-size: 16px;
      font-weight: 600;
      border-radius: 30px;
      cursor: pointer;
      box-shadow: 0 4px 16px rgba(0,168,135,0.3);
      transition: all 0.2s;
    }
    
    .print-button button:hover {
      background: #008B6E;
      transform: translateY(-2px);
      box-shadow: 0 6px 20px rgba(0,168,135,0.4);
    }
    
    @media print {
      body {
        background: white;
        padding: 0;
      }
      
      .report-container {
        box-shadow: none;
        border-radius: 0;
      }
      
      .no-print {
        display: none !important;
      }
      
      .summary-cards {
        break-inside: avoid;
      }
      
      .streams-table {
        break-inside: avoid;
      }
      
      .photo-section {
        break-inside: avoid;
      }
    }
    
    @media (max-width: 600px) {
      body {
        padding: 0;
      }
      
      .report-container {
        border-radius: 0;
      }
      
      .report-header {
        padding: 24px;
      }
      
      .report-header h1 {
        font-size: 22px;
      }
      
      .meta-section {
        flex-direction: column;
        gap: 16px;
        padding: 20px 24px;
      }
      
      .summary-section,
      .streams-section,
      .notes-section {
        padding-left: 24px;
        padding-right: 24px;
      }
      
      .summary-cards {
        grid-template-columns: 1fr;
      }
      
      .card-value {
        font-size: 24px;
      }
      
      .print-button {
        bottom: 16px;
        right: 16px;
      }
      
      .print-button button {
        padding: 12px 20px;
        font-size: 14px;
      }
    }
  `;
}

/**
 * Escape HTML to prevent XSS
 * @param {string} text - Text to escape
 * @returns {string} Escaped text
 */
function escapeHtml(text) {
  if (!text) return '';
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, m => map[m]);
}
